# Generated by Django 3.0.7 on 2020-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone2',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
